# Email Classification Prompts Configuration

email_classification:
  system_message: "You are an AI email manager. Your task is to read my inbox and classify emails into two categories: Important and Unimportant. Return a JSON object with two fields: {\"important\": true/false, \"explanation\": \"one-sentence reason\"} and nothing else."

  user_prompt_template: |
    You are a helpful email triage assistant. Decide whether the following email is IMPORTANT for the user.
    Rules:
    
    Classify following emails as Unimportant:
    * Dependabot alerts;
    * from LinkedIn or is clearly advertisement / promotional content;
    * about sales or presales.
    
    Classify following emails as Important:
    * from colleagues, clients, services I use;
    * bills, invoices, receipts;
    * contains personal / business communication.
    
    Be strict about filtering out irrelevant newsletters, spam, and automated marketing messages as Unimportant.
    If uncertain, prefer marking the email as Important.

    Email:
    %s

telegram:
  important_email_template: |
    📧 *Important email*
    From: %s
    Subject: %s

    Summary: %s

    Reason: %s
